config:
  name: discovery-client
  info: Client micro serive auto discovered by eureka

endpoints:
  restart:
    enabled: true

spring:
  application:
    name: discovery-client
  cloud:
    config:
      enabled: true

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5

---
spring:
  profiles: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud
eureka:
  password: password
  client:
    serviceUrl:
      # defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
      defaultZone: ${vcap.services.routing-eureka-service.credentials.uri}/eureka/
